### ISSUE TITLE
error:问题运行app_real3dportrait.py：配置文件和模型加载警告与错误

### ISSUE THREAD

**Issue by louiseliu** [yerfor/Real3DPortrait#28]
Hello,

首先感谢您开发并分享这个令人兴奁的项目。我在尝试运行`app_real3dportrait.py`时遇到了一些问题，并希望能够得到您的帮助。

### 环境信息
- 操作系统：Windows 11
- Python版本：3.9

所有配置按照作者给你的配置方式进行

### 执行命令
我在尝试执行以下命令时遇到了问题：
dependency conflicts.
openxlab 0.0.34 requires setuptools~=60.2.0, but you have setuptools 69.1.1 which is incompatible.
解决冲突后，运行一直报错
`python inference/app_real3dportrait.py
| WARN: egs/egs_bases/audio2motion/vae.yaml not exist.
| WARN: checkpoints\240210_real3dportrait_orig\th1kh_512_audio2motion\base.yaml not exist.
| load 'model' from 'checkpoints/240210_real3dportrait_orig/audio2secc_vae/model_ckpt_steps_400000.ckpt', strict=True
| WARN: checkpoints\240210_real3dportrait_orig\secc2plane_torso_orig\secc_img2plane_orig.yaml not exist.
Error in sys.excepthook:

Original exception was:`

### 已尝试的解决方案
- 我已经检查了路径设置，并尝试重新下载项目以确保所有文件都完整。
- 我也查阅了项目的文档和issues，但没有找到类似的问题或解决方案。

我想询问是否有我可能忽略的配置步骤，或者是需要下载额外的文件。任何帮助或指导都将非常感激。

谢谢您抽时间查看我的问题。

**Comment by ArcaneLex** [comment]
我同样遇到了这个问题：

Error in sys.excepthook:

Original exception was:`

**Comment by Kizuna-AII** [comment]
The warnings like "checkpoints\240210_real3dportrait_orig\th1kh_512_audio2motion\base.yaml not exist." or "checkpoints\240210_real3dportrait_orig\secc2plane_torso_orig\secc_img2plane_orig.yaml" are harmless, so there should be other problems with your environment.

I notice that the platform you are using is Windows 11, which we have not tested since we do not have Windows machines with a good enough GPU. 

Maybe you can try Debug with some IDE such as VSCode or just add some "print" code to determine where the error actually occurs.

**Comment by laixiao** [comment]
win11同样遇到此问题，看下能否兼容

Error in sys.excepthook:

Original exception was:
